export const foods = [
  {
    id: 1,
    name: "Pizza",
    type: "Fast Food",
    toppings: ["Cheese", "Pepperoni", "Mushrooms"],
  },
  {
    id: 2,
    name: "Burger",
    type: "Fast Food",
    toppings: ["Lettuce", "Tomato", "Cheese"],
  },
  {
    id: 3,
    name: "Tacos",
    type: "Mexican",
    toppings: ["Beef", "Cheese", "Salsa"],
  },
  {
    id: 4,
    name: "Sushi",
    type: "Japanese",
    toppings: ["Salmon", "Avocado", "Rice"],
  },
  {
    id: 5,
    name: "Pasta",
    type: "Italian",
    toppings: ["Marinara", "Parmesan", "Basil"],
  },
  {
    id: 6,
    name: "Hot Dog",
    type: "Fast Food",
    toppings: ["Mustard", "Ketchup", "Onions"],
  },
  {
    id: 7,
    name: "Salad",
    type: "Healthy",
    toppings: ["Lettuce", "Croutons", "Dressing"],
  },
  {
    id: 8,
    name: "Sandwich",
    type: "Snack",
    toppings: ["Ham", "Cheese", "Lettuce"],
  },
  {
    id: 9,
    name: "Ramen",
    type: "Japanese",
    toppings: ["Egg", "Pork", "Green Onions"],
  },
  {
    id: 10,
    name: "Fried Rice",
    type: "Asian",
    toppings: ["Egg", "Carrots", "Peas"],
  },
  {
    id: 11,
    name: "Ice Cream",
    type: "Dessert",
    toppings: ["Chocolate Syrup", "Sprinkles", "Whipped Cream"],
  },
  {
    id: 12,
    name: "Pancakes",
    type: "Breakfast",
    toppings: ["Maple Syrup", "Butter", "Berries"],
  },
  {
    id: 13,
    name: "Waffles",
    type: "Breakfast",
    toppings: ["Syrup", "Strawberries", "Cream"],
  },
  {
    id: 14,
    name: "Steak",
    type: "Main Course",
    toppings: ["Garlic Butter", "Pepper", "Salt"],
  },
  {
    id: 15,
    name: "Chicken Wings",
    type: "Appetizer",
    toppings: ["Buffalo Sauce", "Ranch", "Celery"],
  },
  {
    id: 16,
    name: "Nachos",
    type: "Mexican",
    toppings: ["Cheese", "Jalapeños", "Sour Cream"],
  },
  {
    id: 17,
    name: "Donuts",
    type: "Dessert",
    toppings: ["Glaze", "Sprinkles", "Chocolate"],
  },
  {
    id: 18,
    name: "Omelette",
    type: "Breakfast",
    toppings: ["Cheese", "Spinach", "Ham"],
  },
  {
    id: 19,
    name: "Curry",
    type: "Indian",
    toppings: ["Chicken", "Rice", "Spices"],
  },
  {
    id: 20,
    name: "BBQ Ribs",
    type: "Main Course",
    toppings: ["BBQ Sauce", "Spices", "Honey"],
  }
];
