import "dotenv/config";
import express from "express";
import TodoRouter from './routes/todo.router';

// TODO BACKEND
/**
 * GET: returns Todo| All of them 
 *  - response send all todo's / data
 * GET: by ID: retgurn Todo by ID 
 *  - response send back singular todo
 * POST: requirements / parmaeters / part of the req.body
 *  - id generated by the db on creation
 *  - title
 *  - description
 *  - isComplete (set up in db default value false)
 *  - created_at timestamp
 *  - updated_at timepstamp
 *  - - - RESPONSE: send back new todo
 * PUT/PATCH: requirements / parameters / ID part of the req.params
 *  - part / everything 
 *  - RESPONSE: send back updated todo
 * DELETE: parameters ID part of the req.params
 *  - send 204 status (no content) res.ok
 */

const app = express();

app.use('/todo', TodoRouter);

app.listen(3000, () => console.log("Port started on: " + 3000));